root: true
env:
  browser: true
  es2020: true
extends:
  - tuxsnct
  - tuxsnct/react
  - tuxsnct/typescript
parserOptions:
  project: ./tsconfig.json
rules:
  "@typescript-eslint/no-unused-vars": [1, {varsIgnorePattern: tw}]
